version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Print Hello World
          command: echo "Hello, CircleCI!"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
